name: Build Node binaries for Windows x86

on:
  workflow_dispatch:
  workflow_call:

jobs:
  windows-vs2022:
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        target-node: [20, 22]
        target-arch: [ia32]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          check-latest: true

      - run: yarn install --ignore-engines

      - run: choco install nasm

      - run: yarn start --node-range node${{ matrix.target-node }} --arch ${{ matrix.target-arch }} --output dist

      - name: Check if binary is compiled, skip if download only
        id: check_file
        run: |
          ls dist
          if (Test-Path -Path dist\\*.sha256sum -PathType Leaf) { 
            "EXISTS=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          } else { 
            "EXISTS=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          }

      - uses: actions/upload-artifact@v4
        if: steps.check_file.outputs.EXISTS == 'true'
        with:
          name: node${{ matrix.target-node }}-windows-${{ matrix.target-arch }}
          path: dist\\*
